/**
 * MDM Master Upload Action
 * Handles CSV file upload, parsing, validation, and master creation.
 * Creates a dedicated per-master collection (mdm_<masterName>) with proper indexes.
 */

const { v4: uuidv4 } = require('uuid')
const { getDbClient, safeFindOne, COLLECTIONS, getMasterCollectionName, validateMasterName, parseCSV, validateCSV, createAuditLog, createResponse, createErrorResponse, validateIMSToken, getUserFromParams, checkStorageGuardrails, estimateFileSizeMB, getEnvConfig, getCachedSettings, injectRecordAuditFields, getTimezoneDate, enforceAppPermission } = require('../mdm-utils')

async function main (params) {
  if (params.__ow_method === 'options') return createResponse({})

  const auth = validateIMSToken(params)
  if (!auth.valid) return createErrorResponse(auth.error, 401)

  let client
  try {
    client = await getDbClient(params)

    // App-level RBAC
    const appPerm = await enforceAppPermission(client, params, 'file-upload')
    if (!appPerm.allowed) return appPerm.response

    const user = await getUserFromParams(params, client)
    const { csvContent, displayName, visibility, crudEnabled, allowedOperations, queryableFields, requiredFields, facetableFields, facetsConfig, archivalConfig, schema, description, recordAudit } = params
    const masterName = params.masterName || params.entityName
    let primaryKey = params.primaryKey || null

    if (!csvContent || !masterName) {
      return createErrorResponse('Missing required fields: csvContent, masterName')
    }

    if (!validateMasterName(masterName)) {
      return createErrorResponse('Master name must be lowercase alphanumeric with underscores only (e.g. product_master, stores). No hyphens, no reserved names.')
    }

    // Parse CSV
    const { headers, records } = parseCSV(csvContent)

    // If primaryKey provided, validate it exists in headers
    if (primaryKey && !headers.includes(primaryKey)) {
      return createErrorResponse(`Primary key '${primaryKey}' not found in CSV headers: ${headers.join(', ')}`)
    }

    // If no primaryKey provided, auto-generate master_id
    const autoGeneratedPK = !primaryKey
    if (autoGeneratedPK) {
      primaryKey = 'master_id'
      if (!headers.includes('master_id')) {
        headers.unshift('master_id')
      }
      records.forEach(record => {
        record.master_id = uuidv4()
      })
    }

    // Build schema
    const finalSchema = schema || headers.map(h => ({
      name: h,
      type: 'string',
      required: requiredFields ? requiredFields.includes(h) : h === primaryKey,
      queryable: queryableFields ? queryableFields.includes(h) : false,
      facetable: facetableFields ? facetableFields.includes(h) : false,
      editable: h !== primaryKey
    }))

    // Validate
    const tempMetadata = { primaryKey, schema: finalSchema }
    const validationErrors = validateCSV(headers, records, tempMetadata)
    if (validationErrors.length > 0) {
      return createResponse({ status: 'validation_failed', errors: validationErrors, errorCount: validationErrors.length }, 422)
    }

    client = await getDbClient(params)

    // Storage guardrail checks
    const fileSizeMB = estimateFileSizeMB(csvContent)
    const settingsDoc = await getCachedSettings(client)
    const env = getEnvConfig(params)
    const guardrail = await checkStorageGuardrails(client, {
      newDocumentCount: records.length + 2,
      entity: masterName,
      currentEntityRecords: 0,
      fileSizeMB,
      params
    })
    if (!guardrail.allowed) {
      await client.close()
      return createErrorResponse(`Storage guardrail: ${guardrail.reason}`, 507)
    }

    const metaCol = await client.collection(COLLECTIONS.METADATA)

    // Check if master already exists
    const existing = await safeFindOne(metaCol, { masterName })
    if (existing && existing.status !== 'deleted') {
      return createErrorResponse(`Master '${masterName}' already exists. Use full-update or delta-update instead.`, 409)
    }

    const collectionName = getMasterCollectionName(masterName)

    // Create metadata document
    const fileMetadata = {
      masterName,
      collectionName,
      displayName: displayName || masterName,
      description: description || '',
      originalFileName: `${masterName}.csv`,
      primaryKey,
      status: 'active',
      visibility: visibility || 'private',
      crudEnabled: crudEnabled !== false,
      allowedOperations: allowedOperations || {
        read: true, create: true, update: true, patch: true,
        delete: true, bulkUpdate: true, fullUpdate: true, deltaUpdate: true
      },
      schema: finalSchema,
      facets: {
        enabled: Array.isArray(facetableFields) ? facetableFields.length > 0 : false,
        fields: (facetableFields || []).map(f => {
          const fieldConfig = (facetsConfig && facetsConfig[f]) || {}
          return {
            field: f,
            label: fieldConfig.label || f,
            type: fieldConfig.type || 'value',
            sortBy: fieldConfig.sortBy || 'count',
            sortOrder: fieldConfig.sortOrder || 'desc',
            limit: fieldConfig.limit || 50,
            showCount: fieldConfig.showCount !== false,
            collapsed: fieldConfig.collapsed || false
          }
        }),
        returnWithQuery: true,
        maxValuesPerFacet: 100
      },
      activeVersionId: null,
      schemaVersionId: 'schema-v1',
      recordCount: records.length,

      api: {
        basePath: `/api/mdm/${masterName}`,
        readEnabled: true,
        writeEnabled: crudEnabled !== false,
        bulkEnabled: true
      },
      governance: { owner: user, businessUnit: '' },
      recordAudit: {
        enabled: recordAudit ? !!recordAudit.enabled : false,
        createdAt: recordAudit ? !!recordAudit.createdAt : false,
        updatedAt: recordAudit ? !!recordAudit.updatedAt : false,
        createdBy: recordAudit ? !!recordAudit.createdBy : false,
        updatedBy: recordAudit ? !!recordAudit.updatedBy : false
      },
      lastModifiedBy: user,
      archival: {
        enabled: archivalConfig ? (archivalConfig.enabled !== false) : false,
        threshold: (archivalConfig && archivalConfig.threshold) || (settingsDoc?.archival?.defaultThreshold || 50000),
        retentionDays: (archivalConfig && archivalConfig.retentionDays) || (settingsDoc?.archival?.retentionDays || env.auditRetentionDays),
        keepLatest: (archivalConfig && archivalConfig.keepLatest) || (settingsDoc?.archival?.keepLatest || 10000),
        archiveFormat: (archivalConfig && archivalConfig.archiveFormat) || 'csv',
        notifyEmail: (archivalConfig && archivalConfig.notifyEmail) || '',
        lastArchiveAt: null,
        totalArchived: 0
      },
      createdBy: user,
      createdAt: getTimezoneDate(params),
      updatedAt: getTimezoneDate(params)
    }

    await metaCol.insertOne(fileMetadata)

    // Create per-master collection and insert records
    const masterCol = await client.collection(collectionName)

    const auditConfig = fileMetadata.recordAudit

    const recordDocs = records.map(record => {
      // Inject record-level audit fields into the data payload based on master config
      injectRecordAuditFields(record, auditConfig, user, params, true)

      return {
        primaryKey: record[primaryKey],
        data: record,
        status: 'active',
        deleted: false,
        createdAt: getTimezoneDate(params),
        createdBy: user,
        updatedAt: getTimezoneDate(params),
        updatedBy: user
      }
    })

    await masterCol.insertMany(recordDocs)

    // Create indexes on the per-master collection
    await masterCol.createIndex({ primaryKey: 1 }, { unique: true })
    await masterCol.createIndex({ deleted: 1 })

    // Create indexes for queryable fields (filter columns)
    const queryableList = queryableFields || finalSchema.filter(f => f.queryable).map(f => f.name)
    for (const field of queryableList) {
      try {
        await masterCol.createIndex({ [`data.${field}`]: 1 })
      } catch (e) {
        // Index creation is best-effort
      }
    }

    // Audit
    await createAuditLog(client, {
      masterName,
      operation: 'upload',
      actor: user,
      status: 'success',
      affectedRecords: records.length,

    })

    return createResponse({
      status: 'success',
      master: masterName,
      collectionName,
      recordCount: records.length,
      schema: finalSchema,
      api: fileMetadata.api,
      message: `Successfully uploaded ${records.length} records for master '${masterName}' (collection: ${collectionName})`
    }, 201)
  } catch (error) {
    console.error('Master upload error:', error)
    return createErrorResponse(`Upload failed: ${error.message}`, 500)
  } finally {
    if (client) await client.close()
  }
}

exports.main = main
